# Generated by Django 5.1.2 on 2024-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_post_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(default="", upload_to="post/"),
        ),
    ]
