# Generated by Django 5.1.2 on 2024-10-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(default="", upload_to="posts/images"),
        ),
    ]
