# Generated by Django 5.1.2 on 2024-10-30 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_post_post_description_alter_post_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_description",
        ),
    ]
