# Generated by Django 5.1.2 on 2024-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_post_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_description",
            field=models.TextField(default=""),
        ),
    ]
